# Generated by Django 6.0.5 on 2026-05-27 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'System Logs'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether notification has been read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Notification message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notification title', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Target admin user', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured data'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='message',
            field=models.TextField(help_text='Log message'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='dashboard_n_created_dd91e3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['-timestamp'], name='dashboard_s_timesta_72cfca_idx'),
        ),
    ]
