# Generated by Django 6.0.5 on 2026-05-20 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='produceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Organic sweet potatoes, Fresh Tomatoes', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='price in local currency', max_digits=10)),
                ('quantity', models.CharField(help_text='e.g., 50kg bag, 1 crate', max_length=50)),
                ('village_origin', models.CharField(help_text='village where the produce is located', max_length=100)),
                ('target_town', models.CharField(help_text='nearest town', max_length=100)),
                ('create_at', models.DateField(auto_now_add=True, help_text=True)),
                ('is_available', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
