# Generated by Django 6.0.5 on 2026-05-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producelisting',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
