# Generated by Django 6.0.5 on 2026-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_create_at_to_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producelisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
    ]
