# Generated by Django 6.0.5 on 2026-05-27 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_producelisting_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producelisting',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Produce Listings'},
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='description',
            field=models.TextField(help_text='Detailed description of the produce'),
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether this listing is currently active'),
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='seller',
            field=models.ForeignKey(help_text='Farmer or seller who posted this listing', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='target_town',
            field=models.CharField(help_text='Nearest town', max_length=100),
        ),
        migrations.AlterField(
            model_name='producelisting',
            name='village_origin',
            field=models.CharField(help_text='Village where the produce is located', max_length=100),
        ),
        migrations.AddIndex(
            model_name='producelisting',
            index=models.Index(fields=['-created_at'], name='marketplace_created_74128f_idx'),
        ),
        migrations.AddIndex(
            model_name='producelisting',
            index=models.Index(fields=['is_available'], name='marketplace_is_avai_09890b_idx'),
        ),
    ]
