# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_producelisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producelisting',
            name='video',
            field=models.FileField(
                blank=True,
                help_text='Upload a short video of your harvest',
                null=True,
                upload_to='listing_videos/',
            ),
        ),
    ]
